### ISSUE TITLE
MythicMetal

### ISSUE THREAD

**Issue by ardissaps** [Crendgrim/DynamicCrosshairCompat#1]
It is pretty major and have many equipment, so I guess it worth giving support :
https://www.curseforge.com/minecraft/mc-mods/mythicmetals

**Comment by Crendgrim** [comment]
Have you tried using it combined with the Compat mod?

I'm still waiting for Curseforge to publish it, but it is on Modrinth already: https://modrinth.com/mod/dynamiccrosshaircompat

From my limited testing, it worked fine with Dynamic Crosshair 2.3 + Dynamic Crosshair Compat. What is wrong / missing?

**Comment by ardissaps** [comment]
> Have you tried using it combined with the Compat mod?
> 
> I'm still waiting for Curseforge to publish it, but it is on Modrinth already: https://modrinth.com/mod/dynamiccrosshaircompat
> 
> From my limited testing, it worked fine with Dynamic Crosshair 2.3 + Dynamic Crosshair Compat. What is wrong / missing?

It is working I mean the crosshair model with FVT compatibility that display spesific crosshair shape

**Comment by Crendgrim** [comment]
So.. this issue can be closed? I'm not sure I understand
