### ISSUE TITLE
Compatibility with "Camera Utils"

### ISSUE THREAD

**Issue by UnderMineBlox** [Crendgrim/DynamicCrosshairCompat#10]
I use this mod for the "customizable third person perspectives" but when I go into those modes, the crosshair disappears completely

I do have the 'Show crosshair in third person view' set to 'Yes' , and it works in normal third person view, but not with the Camera Utils perspectives. Is it possible to add compatibility? 

Link to the mod: https://modrepo.de/minecraft/camerautils/overview

**Comment by Crendgrim** [comment]
I looked into this a bit, and any solution from my side would be at best a very ugly hack. This is something that would be much easier with a config option in Camera Utils, but sadly it seems like its author does not want to do it:
https://github.com/henkelmax/camera-utils/issues/10
