### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by blablakali** [Crendgrim/DynamicCrosshairCompat#11]
As soon mas you look at entity, with weapon, game crashes.
Crash-report mentions dynamiccrosshaircompat and bettercombat
[crash-2022-12-03_19.28.49-client.txt](https://github.com/Crendgrim/DynamicCrosshairCompat/files/10146724/crash-2022-12-03_19.28.49-client.txt)

**Comment by Crendgrim** [comment]
This has been fixed already , please update DynamicCrosshair & DynamicCrosshairCompat.
