### ISSUE TITLE
Installs other mods without permission!

### ISSUE THREAD

**Issue by A-T-L-A-S** [Crendgrim/DynamicCrosshairCompat#12]
After installing this mod, I also found "Pick your poison" and "Elytra booster" In the game. I did not install those mods manually nor via curseforge.
They are not installed into the mod folder but instead appear in the .fabric/processed mods folder.

**Comment by Crendgrim** [comment]
As explained on the CurseForge page, I have no idea what has caused Gradle to bundle those two mods (and if those, why not all of the ones in my dev environment). Either way, I have pushed a new version to Modrinth (available) and CurseForge (pending) and will pay attention to this in the future. Apologies for the inconvenience, this was definitely not an intended behaviour.
