### ISSUE TITLE
crash with dynamiccrosshair

### ISSUE THREAD

**Issue by lostopkk** [Crendgrim/DynamicCrosshairCompat#13]
https://i.imgur.com/G9FlZSS.png

**Comment by Crendgrim** [comment]
That is amusing. I did not know Fabric's dependency algorithm worked like that; and then I assume that your mod loader of choice forces the 5.0 -> 5.0b update?

Either way, manually upgrade your DynamicCrosshair to release 5.0 (*not* beta 5.0b), and it will work fine. I will archive all beta versions later so it hopefully doesn't happen again.
