### ISSUE TITLE
Compat Error Crash

### ISSUE THREAD

**Issue by ereese99** [Crendgrim/DynamicCrosshairCompat#15]
I get a crash when trying to access a Create conveyor belt
[message (3).txt](https://github.com/Crendgrim/DynamicCrosshairCompat/files/11069848/message.3.txt)

**Comment by Crendgrim** [comment]
Thanks for the report! Silly oversight on my part, I pushed version 3.2.1 to fix this.

**Comment by Crendgrim** [comment]
(CurseForge is being a bit unstable right now; I'm not sure whether the publish worked. It's on Modrinth already and will be on CF once it calms down.)
