### ISSUE TITLE
Log spam with Create 0.5.1

### ISSUE THREAD

**Issue by TheFurryDevil** [Crendgrim/DynamicCrosshairCompat#17]
When using this with Create 0.5.1 the log is being spammed with errors.
[latest.log](https://pastebin.com/BVd9j6W3)

**Comment by Crendgrim** [comment]
Oof, they moved around every single class. Thanks for the report. I pushed DCC 3.3.2 that should work fine with Create 0.5.1 :)

**Comment by TheFurryDevil** [comment]
> Note that I didn't verify all the interactions; if you find any where the wrong crosshair is shown, please do let me know!

Actually, curved train track blocks are not showing any cursor. Seems like for 0.5.0 it didn't either. I don't know if that's feasible since they're not real blocks...

**Comment by Crendgrim** [comment]
In what situation does the cursor not appear? If I pull out train tracks and start making a curve, the block crosshair is always shown.

**Comment by TheFurryDevil** [comment]
Like with empty hands, when looking at the curved parts. For straight parts it shows the crosshair, for the curved parts it doesn't, so "If targeting" is not true for them I guess.

**Comment by Crendgrim** [comment]
I see. I have tried to fix this, but it's very weird what they do and I have yet to understand it. So I haven't been successful yet.
