### ISSUE TITLE
[fabric 1.19.2] Exception occurred during evaluation of API bettercombat

### ISSUE THREAD

**Issue by dadoirie** [Crendgrim/DynamicCrosshairCompat#18]
https://mclo.gs/QMlGfRz

look like better combat or dynamic cross-hair changed something which broke their compatibility - hope this log shows whats wrong

confirmed with a instance only with those mods present:

[✔] bettercombat-fabric-1.7.1 1.19
[✔] cloth-config-8.2.88-fabric
[✔] dynamiccrosshair-5.6.1 1.19.2-fabric
[✔] dynamiccrosshair-compat-3.3.2 1.19.2
[✔] fabric-api-0.76.0 1.19.2
[✔] player-animation-lib-fabric-1.0.2

error/s (each error is for one zombie pointed at) at line 280 (https://mclo.gs/QMlGfRz#L280)

**Comment by Crendgrim** [comment]
Oof, that's a silly I did when trying to harden DynamicCrosshair against broken APIs, forgot about the one case where I actually use exceptions. I pushed DynamicCrosshair 5.6.2 which should fix this. Thanks for the report!
