### ISSUE TITLE
Please add compatibility with Bridging Mod

### ISSUE THREAD

**Issue by RMF-AndyPlayz** [Crendgrim/DynamicCrosshairCompat#21]
[Link](https://modrinth.com/mod/bridging-mod)

not sure what else to write but it would be awesome if you can add it!

**Comment by Crendgrim** [comment]
From what I remember, that mod draws its own crosshair for the place-around mode, correct?

**Comment by RMF-AndyPlayz** [comment]
I think so.
Here's what the crosshair looks like without dynamic crosshair:
![image](https://github.com/Crendgrim/DynamicCrosshairCompat/assets/58617083/122f4e38-58e3-4be6-b1d6-7220ba2dac23)

Here's what it looks like with dynamic crosshair:
![image](https://github.com/Crendgrim/DynamicCrosshairCompat/assets/58617083/40569445-7bd5-47f4-b013-ea646ce8b7e5)

If you want a video of me demonstrating, lmk

**Comment by Crendgrim** [comment]
Oh interesting, it removes the reach-around crosshair. It might be a different mod then, or an update broke it. I remember playing around with a mod that allowed for reach-around placing that had at least a similar crosshair to the bridging mod, and it worked fine together. I will investigate!

**Comment by Crendgrim** [comment]
See the linked PR and also CloudG360/BridgingMod#1.

If the author accepts, this should be fixed with the next release of BridgingMod :)

**Comment by Crendgrim** [comment]
And it has been merged in BridgingMod
