### ISSUE TITLE
Compatibility with Mindful Darkness

### ISSUE THREAD

**Issue by IntM4rco** [Crendgrim/DynamicCrosshairCompat#22]
https://modrinth.com/mod/mindful-darkness

(It's probably impossible)

**Comment by IntM4rco** [comment]
(I should clarify that the mod works but the crosshair becomes so dark that it is nearly invisible.)

**Comment by Crendgrim** [comment]
DynamicCrosshair allows you to modify the crosshair colour. Does that help?

**Comment by IntM4rco** [comment]
I already tried it.
No, it doesnt work

**Comment by IntM4rco** [comment]
I'll send u a video

**Comment by IntM4rco** [comment]
### As you can see there is a difference even when I select a color with the dark gui active.
https://github.com/Crendgrim/DynamicCrosshairCompat/assets/124934175/38cdd7b5-7ec9-4fad-afaa-472cc5f8ed59

**Comment by IntM4rco** [comment]
Can you fix it or should I contact the Mindful Darkness devs?

**Comment by Crendgrim** [comment]
I have not looked into it yet. From looking at the mod pages, it has a configuration where you can add exclusions. You could try to add the following to the "paths" config: `!dynamiccrosshair:textures/gui/crosshairs.png`

**Comment by IntM4rco** [comment]
Ty so much, ill try it.
