### ISSUE TITLE
Port to 1.20.2

### ISSUE THREAD

**Issue by verixyt3** [Crendgrim/DynamicCrosshairCompat#24]
Hello, I'm asking you to make a version for _1.20.2 fabric or quilt on Modrinth_, **thank you very much!**

**Comment by Crendgrim** [comment]
Please use proper titles when filing bug reports on GitHub projects (or anywhere), thank you. "asking" does not make for a good subject at all.

That being said, a port to 1.20.2 will happen whenever I find time.
