### ISSUE TITLE
compat with HWG broken after 2.0.0 update

### ISSUE THREAD

**Issue by temyy** [Crendgrim/DynamicCrosshairCompat#29]
title, hwg recently updated to 2.0.0 which reworked things and the crosshair compat is broken now with a LOT of log spam
[latest.log](https://github.com/Crendgrim/DynamicCrosshairCompat/files/13622204/latest.log)

**Comment by Crendgrim** [comment]
Thanks for the report, should hopefully be working properly with 3.6.1 now
