### ISSUE TITLE
Error spawming

### ISSUE THREAD

**Issue by TheLegendofSaram** [Crendgrim/DynamicCrosshairCompat#36]
it seems that when the compat doesnt have an item or an action registered in it it just spawms the log with errors. So far i have encaunter 2 mods which triggers this reaction. [Farmer's Delight Refabricated](https://modrinth.com/mod/farmers-delight-refabricated) and [AdventureZ](https://modrinth.com/mod/adventurez) the items i saw in the log where "ender_flaute" and some others for [AdventureZ](https://modrinth.com/mod/adventurez) and "ItemStackInventory" and "CuttingBoardBlockEntity " for [Farmer's Delight Refabricated](https://modrinth.com/mod/farmers-delight-refabricated).
Here one of the logs
[latest.log](https://github.com/Crendgrim/DynamicCrosshairCompat/files/14860939/latest.log)

**Comment by Crendgrim** [comment]
Apologies for the delay, should finally be fixed!
