### ISSUE TITLE
Origin Realms support

### ISSUE THREAD

**Issue by Fernan181** [Crendgrim/DynamicCrosshairCompat#38]
Support for the custom content on the Origin Realms server.
Server IP: play.originrealms.com
Official Webpage: https://originrealms.com/

**Comment by Crendgrim** [comment]
Not interested in developing or maintaining this myself, apologies. It's a shifting target that would require serious development and testing time that I don't have to spare. Also, as it is a feature set of just a single server, knowing when to enable these features would be a bit tricky. Someone interested in this could make a DynamicCrosshair add-on of their own, though! That could just be always active and thus easier to maintain.
