### ISSUE TITLE
Crash on Server 

### ISSUE THREAD

**Issue by ereese99** [Crendgrim/DynamicCrosshairCompat#40]
[crash-2024-05-19_12.20.40-client.txt](https://github.com/Crendgrim/DynamicCrosshairCompat/files/15379320/crash-2024-05-19_12.20.40-client.txt)

**Comment by Crendgrim** [comment]
DCC is a client-only mod, at least for the time being.

**Comment by ereese99** [comment]
Client-side crash WHILE on server is how I should phrase it

**Comment by Crendgrim** [comment]
Hm, I cannot replicate this crash. Do you know what weapon you are holding when it crashes? Or what entity (if any) you are targeting? Are there any ways it does or does not crash?

**Comment by Crendgrim** [comment]
Let me know if you have any further information to track this down.
