### ISSUE TITLE
Log spam when paired with Oh The Biomes You'll Go on 1.19.2

### ISSUE THREAD

**Issue by TheGamerCanine** [Crendgrim/DynamicCrosshairCompat#45]
Minecraft 1.19.2
Fabric 0.16.0
Fabric API 0.77.0
Dynamic Crosshair 5.7.1
Dynamic Crosshair Compat 3.3.3
Oh The Biomes You'll Go 2.0.1.6

![image](https://github.com/user-attachments/assets/c684d3a9-efd4-4c89-9862-783429ac5844)
I've noticed any time I hover my crosshair over a block I get spammed with this NoClassDefFoundError specifically referring to the Baobab Fruit Block from Oh The Biomes You'll Go.

**Comment by Crendgrim** [comment]
Hm, something's fucky with gradle. Should be fixed in 3.3.4
