### ISSUE TITLE
Support for ewewukek's Musket Mod

### ISSUE THREAD

**Issue by zaeonNineZero** [Crendgrim/DynamicCrosshairCompat#6]
Should be simple enough, just add the Musket Mod's Musket, Musket with Bayonet, and Flintlock Pistol as recognized ranged weapons for the dynamic crosshair.

Link to the mod in question:
https://www.curseforge.com/minecraft/mc-mods/ewewukeks-musket-mod

**Comment by Crendgrim** [comment]
Added support in DynamicCrosshairCompat 1.10 :)
