### ISSUE TITLE
Applied Energistics 2 is not compatible with Dynamic crosshair compat

### ISSUE THREAD

**Issue by dbasak1234** [Crendgrim/DynamicCrosshairCompat#9]
## After loading dynamic crosshair compat and dynamic crosshair mod with applied energistics 2 and wireless terminals, the game is crashing instantly when i am trying to take an ae2 item in my hand with the error given below.

![image](https://user-images.githubusercontent.com/37909678/202807725-39f10963-5fde-4c4e-af90-0242a525844a.png)
![image](https://user-images.githubusercontent.com/37909678/202807817-5ee76cc4-1931-495a-8eef-4811c45f8f01.png)

**Comment by Crendgrim** [comment]
Thank you for the report! AE2 moved a class upstream. Fixed in 1.11.1 :)
